### ISSUE TITLE
Katalog poziadaviek

### ISSUE THREAD

**Issue by Lighttik** [TIS2019-FMFI/top-quark-reconstruction#1]
1. Introduction
1.1 Purpose of requirements document
1.2 Scope of the product
1.3 Definitions, acronyms and abbreviations
1.4 References
1.5 Overview of the remainder of the document
2. General description
2.1 Product perspective
2.2 Product functions
2.3 User characteristics
2.4 General constraints
2.5 Assumptions and dependencies
3. Specific requirements: Covering functional, non-functional and interface requirements
4. Appendices
Index

**Comment by pavelpetrovic** [comment]
font menej narrow


1.1 upravit formulacie
    co je KP nemusi kazdy rozumiet
    a TIS je len druhotny ciel

1.2. kde sa zabezpeci plynulost aplikacie ???

1.3. co znamena symbolicka matematicka kniznica?

1.4. aspon nadpis, ktory nie je skratka - co su tie polozky?

2.1. tt-barevent  - chyba v slovniku pojmov
     celkovo formulacia je tazko zrozumitelna

2.2. rozviest podrobnejsie aj vstupy aj vystupy

2.3. jednoznacnejsie uviest, ci system pozna iba jednu pouzivatelsku rolu

poziadavky v casti 3 dokumentu maju kazda svoje oznacenie

poziadavky formulovat ako hodnotu, ktoru pouzivatel od systemu ziska, resp.
co system ponuka, zabezpecuje, robi, kontroluje, ...

ako dobre to zvladli => vsetko ovela podrobnejsie definovat a popisat

vsetko ostatne podrobnejsie, presnejsie, konkretnejsie,
veci v rozhrani patria do funkcionality

**Comment by pavelpetrovic** [comment]
pisomne - textove
dva - tri
o pouzivatelskych roliach:
 - mozno staci len jedna rola, ale otazka je, ci treba viacero rovnocennych pouzivatelov (tam by som videl uzitok), ale asi sa so systemom ma dat pracovat iba po prihlaseni sa

poziadavky maju byt ocislovane (alebo inak oznacene)
vsetky poziadavky by mali byt formulovane ako hodnota pre pouzivatela, ktoru aplikacia ponuka.

**Comment by pavelpetrovic** [comment]
k novej verzii KP:
- 2.2. vyzera nedopisany
- 3.1.1. nema ziadnu informacnu hodnotu
- 3.1.2. "Bude natrénovaná" => samo sa to urobilo
- 3.1.3. "data z metody" compile error
- 3.1.4 moznost spustat experimenty vyuzivajuce rozne algoritmy nezavisle a samostatne
  sa zaznamenajú do grafu => co to znamena?
- Spúšťanie => akonahle nahram subor, vsetko sa spusti automaticky?
podrobne specifikovat vsetko
- "Systém bude human readable" => asi nie system
3.1.9. zistit a upresnit
