### ISSUE TITLE
Upravit vstup (ROOT)

### ISSUE THREAD

**Issue by Lighttik** [TIS2019-FMFI/top-quark-reconstruction#11]

**Comment by pavelpetrovic** [comment]
Trochu som sa teda na servri pohral s tým ROOT súborom.
Je to pomerne jednoduché. Nejde ani tak o stromovú štruktúru ako o obyčajnú tabuľku, resp. niekoľko tabuliek.

súbor obsahuje tzv. "keys" - to sú jednotlivé tabuľky.

v prípade súboru, ktorý tam máte, sú tam dva keys: signal_permutation a background_permutation.

tieto tabuľky sú typu TTree

TTree pozostáva z "branchov", čo sú v princípe stĺpce tabuľky (typ TBranch)

vnútri branchov sú lístočky (TLeaf), ktorých tam asi môže byť aj viac, ale v tomto súbore je vždy len jeden a volá sa rovnako ako jeho branch.

v lístočkoch sú schované hodnoty (TLeaf.GetValue()) pre každý jeden "entry" - čiže riadky tabuľky, entry je index do volania GetValue(i).

spravil som pre Vás tri programy v priečinku src/palo, čiže po prihlásení najskôr zadať

cd src/palo
ls

1. src/palo/showInBrowser.py   - umožňuje prezeranie celého ROOT súboru v grafickom okne funguje to ale iba ak sa na server prihlásite z nejakého Linuxu pomocou
 ssh atlas23.dnf.fmph.uniba.sk -X
(potrebujete tiež pridať svoj kľúč z toho Linuxu, ak ste doteraz chodili iba z Windows, tak ako som to robil ja)

2. src/palo/dumpROOT.py  - umožňuje vylistovanie celého obsahu súboru (zvlášť štruktúra a zvlášť dáta) v textovej podobe pomocou funkcií Print() a Scan(), toto ale nechcete používať, pretože dáta vypisuje len s obmedzenou presnosťou... ale na pozretie štruktúry a obsahu súboru je to fajn. Najlepšie je presmerovať výstup do súboru, aby sa to dalo pozerať a nezahltilo terminál. Príklad:

python dumpROOT.py > dumped_root.txt

3. src/palo/dumpDetails.py - vydumpuje všetko zo súboru s tým, že hodnoty vyťahuje cez GetValue(), takže nie sú v obmedzenej presnosti, takto to chcete robiť aj Vy. Opäť odporúčam presmerovať výstup, napr.

python dumpDetails.py > details.txt

možno však iné súbory budú obsahovať aj iné veci a štruktúry, takže potom to bude treba podľa toho prispôsobiť...

veľa zdaru!!
