### ISSUE TITLE
Vytvorit datovy model pre databazu

### ISSUE THREAD

**Issue by Lighttik** [TIS2019-FMFI/top-quark-reconstruction#12]

**Comment by pavelpetrovic** [comment]
* prosim do dokumentu navrh pridat vysvetlenie datoveho modelu, zatial tomu rozumiem tak, ze v cervenej tabulke je iba jedno z ID-ciek do zltych tabuliek platne, aj tak by som do cervenej tabulky pridal "typ_experimentu" - cislo typu, napr. 1 - KLFITTER, 2 - DNN, ale mozno to myslite celkom inak...
* dalej nerozumiem naco je tabulka s trenovacimi datami (?)
