### ISSUE TITLE
KlFitter (nastudovat si)

### ISSUE THREAD

**Issue by Lighttik** [TIS2019-FMFI/top-quark-reconstruction#5]

**Comment by Lighttik** [comment]
https://github.com/KLFitter/KLFitter

Pozrite si to aspon trochu, nech to vieme implementovat ;)

**Comment by pavelpetrovic** [comment]
good first issue label sluzi na to, ze ked sa niekto chce zapojit do open-source developmentu, tak si najde projekty, kde je takto oznaceny issue a zacne tam s tym projektom pomahat.

takze pokial nehladate externych pomocnik z radov open-source komunity, tak to nie je prave idealny label. :)
