### ISSUE TITLE
Vytvorit UML diagramy

### ISSUE THREAD

**Issue by Lighttik** [TIS2019-FMFI/top-quark-reconstruction#7]

**Comment by Lighttik** [comment]
Diagramy pridane do dokumentacie

**Comment by Lighttik** [comment]
Pridane diagramy :)
[https://github.com/TIS2019-FMFI/top-quark-reconstruction/tree/documentation/Desktop/Skola/5.%20Semester/top-quark-reconstruction-master/docs](url)

**Comment by pavelpetrovic** [comment]
pozreli sme si spolocne diagramy, tu su komentare, prosim, zapracovat:

* v stavovom diagrame musi mat kazdy stavovy prechod popis: pri akej akcii, udalosti alebo po akom case k nemu dochadza
* jednotlive stavy maju byt *pasivne*, to znamena, nemaju to byt akcie. z nazvu stavu "open file" sa zda, ze ide o akciu otvorit subor. ak sa mysli pasivny stav, ze subor je otvoreny, priliehavejsi nazov by bol "file is open"
* celkovo tento diagram vyzera skor ako activity diagram a nie state diagram, kde by mali byt pasivne stavy a nie akcie, prosim o novu verziu

**Comment by pavelpetrovic** [comment]
ku komponentovemu diagramu:

* chyba mi na strane servra nejaky php komponent, ktory bude odchytavat requesty od klienta, alebo tam php nebude? potom treba upravit dokument navrh
* napr. ak to bude priamo pythonovy webovy server?
