### ISSUE TITLE
Vyvorit navrh systemu

### ISSUE THREAD

**Issue by Lighttik** [TIS2019-FMFI/top-quark-reconstruction#9]

**Comment by pavelpetrovic** [comment]
* treba si ujasnit, ci vstupy sa budu konvertovat automaticky vzdy ako sucast behu experimentu, alebo, ci sa ukladaju aj trvalo v nejakej podobe - napr. vo forme json (ako mate teraz uvedene v dokumente navrh)
* do casti o Kerase a Klfitteri treba rozpisat podrobne ako ich budete pouzivat (priamo volania a poradie v akom budu pouzite)
* treba zistit na co budete pouzivat LWTNN
